# Generated by Django 5.1.15 on 2026-10-06 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOutboxLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('client_mutation_id', models.CharField(blank=True, max_length=128)),
                ('mutation_type', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('server_entity_id', models.UUIDField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Sync Outbox Log',
                'verbose_name_plural': 'Sync Outbox Logs',
                'constraints': [models.UniqueConstraint(fields=('business', 'idempotency_key'), name='uq_tenant_sync_idempotency_key')],
            },
        ),
    ]
