# Generated by Django 5.1.15 on 2026-10-06 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('businesses', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=64)),
                ('client_invoice_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid')], default='PAID', max_length=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit / Debit Card'), ('UPI', 'UPI / QR Code'), ('CREDIT', 'Khata / Customer Credit'), ('BANK_TRANSFER', 'Bank Transfer'), ('MIXED', 'Split / Mixed Payment')], default='CASH', max_length=24)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='businesses.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1.0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequenceTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.CharField(db_index=True, default='2026-27', max_length=16)),
                ('prefix', models.CharField(default='INV-', max_length=16)),
                ('current_sequence', models.BigIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='branches.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Invoice Sequence Tracker',
                'verbose_name_plural': 'Invoice Sequence Trackers',
                'constraints': [models.UniqueConstraint(fields=('business', 'branch', 'fiscal_year', 'prefix'), name='uq_invoice_sequence_tracker')],
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('business', 'invoice_number'), name='uq_sale_business_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('business', 'idempotency_key'), name='uq_sale_business_idempotency_key'),
        ),
    ]
