# Generated by Django 5.1.15 on 2026-10-06 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('business_type', models.CharField(choices=[('RETAIL', 'Retail Shop / POS'), ('JEWELLERY', 'Jewellery & Gold Business'), ('ELECTRONICS', 'Electronics & Appliances'), ('GROCERY', 'Grocery & Supermarket'), ('WHOLESALE', 'Wholesale Trader'), ('DISTRIBUTOR', 'Distributor / Supply Chain'), ('SERVICE', 'Service Business'), ('MANUFACTURING', 'Small Manufacturing'), ('RESTAURANT', 'Restaurant / Cafe'), ('GENERAL', 'General Trading')], default='GENERAL', max_length=32)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('currency_symbol', models.CharField(default='₹', max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('tax_identification_number', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('logo_storage_key', models.CharField(blank=True, max_length=255)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=16)),
                ('quotation_prefix', models.CharField(default='EST-', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='businesses.business')),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_users', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Business Membership',
                'verbose_name_plural': 'Business Memberships',
            },
        ),
    ]
